#: schema https://json.schemastore.org/cargo.json
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "memospot"
version = "0.1.2"
authors = ["Lincoln Nogueira"]
edition = "2021"
license = "MIT"
repository = "https://github.com/lincolnthalles/memospot"
description = "Memospot is a desktop version of Memos, a beautiful, privacy-first, lightweight note-taking service."

[build-dependencies.tauri-build]
features = ["config-toml"]
version = "1.5"

[dependencies.config]
path = "../crates/config"
version = "0.0.1"

[dependencies.homedir]
path = "../crates/homedir"
version = "0.1.1"

[dependencies.portpicker]
path = "../crates/portpicker"
version = "0.0.1"

[dependencies.serde_yaml]
version = "0.9.31"
default-features = false

[dependencies.log]
version = "0.4.20"

[dependencies.native-dialog]
version = "0.7.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.tauri-cli]
version = "1.5.10"

[dependencies.tokio]
version = "1.36.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"

[target.'cfg(target_os = "macos")'.dependencies.window-shadows]
version = "0.2.2"

[target.'cfg(windows)'.dependencies.winreg]
version = "0.52.0"

[dependencies.log4rs]
features = ["background_rotation", "config_parsing", "gzip", "yaml_format"]
version = "1.3.0"

[dependencies.reqwest]
features = ["brotli", "deflate", "gzip"]
version = "0.11.24"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.tauri]
default-features = true
features = [
    "config-toml",
    "http-request",
    "process-exit",
    "process-relaunch",
    "protocol-asset",
    "shell-all",
    "window-all",
]
version = "1.5"

[dependencies.url]
features = ["serde"]
version = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
