#: schema https://json.schemastore.org/cargo.json
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "memospot"
version = "0.1.4"
authors = ["Lincoln Nogueira"]
edition = "2021"
license = "MIT"
repository = "https://github.com/lincolnthalles/memospot"
description = "Memospot is a desktop version of Memos, a beautiful, privacy-first, lightweight note-taking service."

[build-dependencies.tauri-build]
features = ["config-toml"]
version = "1.5"

[dependencies.config]
path = "../crates/config"
version = "0.0.1"

[dependencies.entity]
path = "../crates/entity"
version = "0.18.2"

[dependencies.homedir]
path = "../crates/homedir"
version = "0.1.1"

[dependencies.migration]
path = "../crates/migration"
version = "0.1.0"

[dependencies.portpicker]
path = "../crates/portpicker"
version = "0.0.1"

[dependencies.writable]
path = "../crates/writable"
version = "0.0.1"

[dependencies.anyhow]
version = "1.0.80"

[dependencies.async_zip]
version = "0.0.16"
features = ["zstd", "tokio-fs"]

[dependencies.chrono]
version = "0.4.35"
default-features = false

[dependencies.itertools]
version = "0.12.1"
default-features = false

[dependencies.log]
version = "0.4.21"

[dependencies.log4rs]
features = ["background_rotation", "config_parsing", "gzip", "yaml_format"]
version = "1.3.0"

[dependencies.native-dialog]
version = "0.7.0"

[dependencies.path-clean]
version = "1.0.1"

[dependencies.reqwest]
features = ["gzip"]
version = "0.11.26"

[dependencies.semver]
version = "1"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.serde_yaml]
version = "0.9.31"
default-features = false

[dependencies.sea-orm]
version = "0.12"
features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"]

[dependencies.tauri]
version = "1.6.1"
default-features = true
features = ["shell-sidecar", "shell-open", "config-toml", "window-all"]

[dependencies.tauri-utils]
version = "1.5.2"
default-features = false

[dependencies.tempfile]
version = "3.8.1"

[dependencies.tokio]
version = "1.36.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"

[target.'cfg(windows)'.dependencies.winreg]
version = "0.52.0"

[dependencies.url]
features = ["serde"]
version = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
