#: schema https://json.schemastore.org/cargo.json
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "memospot"
version = "0.1.7"
authors = ["Lincoln Nogueira"]
edition = "2021"
license = "MIT"
repository = "https://github.com/memospot/memospot"
description = "Memospot is a desktop version of Memos, a beautiful, privacy-first, lightweight note-taking service."

# [lib]
# name = "memospot_lib"
# crate-type = ["staticlib", "cdylib", "rlib", "lib"]

[build-dependencies.tauri-build]
features = ["config-toml"]
version = "2.0.0-rc"

[dependencies.config]
path = "../crates/config"
version = "0.0.2"

[dependencies.dialog]
path = "../crates/dialog"
version = "0.0.1"

[dependencies]
encoding_rs = "0.8.34"
home = "0.5.9"
once_cell = "1"
os_pipe = "1"
shared_child = { version = "1.0" }
tauri-plugin-fs = "2.0.0-rc"
tauri-plugin-process = "2.0.0-rc"
tauri-plugin-shell = "2.0.0-rc"

[dependencies.tauri-plugin-http]
default-features = false
version = "2.0.0-rc"

[dependencies.homedir]
path = "../crates/homedir"
version = "0.1.1"

[dependencies.migration]
path = "../crates/migration"
version = "0.1.3"

[dependencies.portpicker]
path = "../crates/portpicker"
version = "0.0.1"

[dependencies.writable]
path = "../crates/writable"
version = "0.0.1"

[dependencies.anyhow]
version = "1.0.81"

[dependencies.async_zip]
version = "0.0.17"
features = ["zstd", "tokio-fs"]

[dependencies.chrono]
version = "0.4.35"
default-features = false

[dependencies.itertools]
version = "0.13.0"

[dependencies.log]
version = "0.4.21"

[dependencies.log4rs]
features = ["background_rotation", "config_parsing", "gzip", "yaml_format"]
version = "1.3.0"

[dependencies.path-clean]
version = "1.0.1"

[dependencies.reqwest]
features = ["gzip"]
version = "0.12.1"

[dependencies.semver]
version = "1"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.serde_yaml]
version = "0.9.33"
default-features = false

[dependencies.sea-orm]
version = "1.0"
default-features = false
features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"]

[dependencies.tauri]
version = "2.0.0-rc"
default-features = true
features = [
    "config-toml",
]

[dependencies.tauri-utils]
version = "2.0.0-rc"
default-features = false

[dependencies.tempfile]
version = "3.10.1"

[dependencies.tokio]
version = "1.36.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"

[target.'cfg(windows)'.dependencies.winreg]
version = "0.52.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.0.0-rc"

[dependencies.url]
features = ["serde"]
version = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
