# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
authors = ["Lincoln Nogueira"]
description = "Memospot is a desktop version of Memos, a beautiful, privacy-first, lightweight note-taking service."
edition = "2021"
license = "MIT"
name = "memospot"
repository = "https://github.com/lincolnthalles/memospot"
version = "0.1.0"

[build-dependencies.tauri-build]
features = ["config-toml"]
version = "1.5"

[dependencies.home-dir]
path = "src/home-dir"
version = "0.1.1"

[dependencies.log]
version = "0.4.20"

[dependencies.native-dialog]
version = "0.6.4"

[dependencies.serde_json]
version = "1.0"

[dependencies.tauri-cli]
version = "1.5.5"

[dependencies.tokio]
version = "1.33.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"

[target.'cfg(target_os = "macos")'.dependencies.window-shadows]
version = "0.2.2"

[target.'cfg(windows)'.dependencies.winreg]
version = "0.51.0"

[dependencies.log4rs]
features = ["background_rotation", "config_parsing", "gzip", "yaml_format"]
version = "1.2.0"

[dependencies.reqwest]
features = ["brotli", "deflate", "gzip"]
version = "0.11.22"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.tauri]
default-features = true
features = [
    "config-toml",
    "http-request",
    "process-exit",
    "process-relaunch",
    "protocol-asset",
    "shell-all",
    "window-all",
]
version = "1.5"

[dependencies.url]
features = ["serde"]
version = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
