# https://github.com/estk/log4rs#quick-start
appenders:
  file:
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    path: "memos.log"
    kind: rolling_file
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: logs/memos.{}.gz
        count: 5
        base: 1
root:
  # debug | info | warn | error | off
  level: error
  appenders:
    - file
