use build_utils::{find_target_dir, find_workspace_root};

#[cfg(unix)]
use std::os::unix::fs::{MetadataExt, PermissionsExt};
use std::{env, fs, path::PathBuf, process::Command};

struct ShortcutBinding {
    /// The name of the shortcut, used for generating accelerator constants.
    name: &'static str,
    /// The command associated with the shortcut.
    command: &'static str,
    /// The accelerator string for the shortcut.
    accelerator: &'static str,
    /// The key codes that trigger the shortcut on the frontend.
    codes: &'static [&'static str],
}

macro_rules! shortcut_bindings {
    (
        $(
            $name:ident => {
                command: $command:literal,
                accelerator: $accelerator:literal,
                codes: [$($code:literal),+ $(,)?],
            }
        ),+ $(,)?
    ) => {
        vec![
            $(
                ShortcutBinding {
                    name: stringify!($name),
                    command: $command,
                    accelerator: $accelerator,
                    codes: &[$($code),+],
                },
            )+
        ]
    };
}

fn generate_shortcut_artifacts() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap_or_default());
    if out_dir.as_os_str().is_empty() {
        return;
    }

    let bindings: Vec<ShortcutBinding> = include!("src/shortcut_bindings.in.rs");

    let mut conditions = format!("{:>4}switch (e.code) {{\n", "");
    for binding in &bindings {
        for code in binding.codes {
            let cmd = binding.command;
            conditions.push_str(&format!(
                "        case \"{code}\":\n            cmd = \"{cmd}\";\n        break;\n"
            ));
        }
    }
    conditions.push_str("        default: break;\n    }");

    let debug = if cfg!(debug_assertions) {
        "console.warn('Memospot shortcut polyfill loaded successfully.');"
    } else {
        ""
    };

    let js = format!(
        r#"
/*
* Shortcut polyfill.
*
* Auto-generated by build.rs from src/shortcut_bindings.in.rs.
*/
document.addEventListener("keydown", (e) => {{
    if (!(e.ctrlKey || e.metaKey)) return;

    let cmd = null;
{conditions}
    if (!cmd) return;

    e.preventDefault();
    window.__TAURI_INTERNALS__.invoke(cmd);
}});
{debug}
"#
    );

    let mut accel = String::new();
    for binding in &bindings {
        accel.push_str(&format!(
            "#[allow(dead_code)]\npub const {}: &str = \"{}\";\n",
            binding.name, binding.accelerator
        ));
    }

    fs::write(out_dir.join("shortcut_polyfill.js"), js)
        .expect("failed to write generated shortcut polyfill");
    fs::write(out_dir.join("shortcut_accelerators.rs"), accel)
        .expect("failed to write generated shortcut accelerators");
    println!("cargo:rerun-if-changed=src/shortcut_bindings.in.rs");
}

/// Ensure that the build dependencies exist in some form.
///
/// This makes the linter happy when the repository is not fully set up.
///
/// - Create UI build directory.
/// - Create dummy server binaries in case they don't exist.
///   > The Tauri build hook will download the proper binaries later.
/// - Set the executable bit on valid UNIX server binaries.
fn ensure_deps() {
    let workspace_root = find_workspace_root().expect("Failed to detect workspace root!");

    let src_ui = workspace_root.join("src-ui/build");
    fs::create_dir_all(&src_ui).ok();

    let server_dist = workspace_root.join("server-dist");
    fs::create_dir_all(&server_dist).ok();

    let dist_path = server_dist
        .canonicalize()
        .expect("Failed to canonicalize server-dist path!");

    const TARGETS: [&str; 5] = [
        "x86_64-unknown-linux-gnu",
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-msvc.exe",
        "aarch64-pc-windows-msvc.exe",
    ];
    for target in TARGETS {
        let target_bin = dist_path.join(format!("memos-{target}"));

        if !target_bin.exists() {
            #[cfg(feature = "unittest")]
            {
                std::fs::File::create(&target_bin).expect("Failed to create dummy binary!");
            }
            #[cfg(not(feature = "unittest"))]
            {
                continue;
            }
        }

        #[cfg(unix)]
        {
            let meta = fs::metadata(&target_bin).expect("Failed to get file metadata!");
            if meta.size() < 1024 {
                continue;
            }
            let mut perms = meta.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&target_bin, perms).expect("Failed to set file permissions!");
        }
    }
}

/// Cleanup dummy server binaries.
///
/// Prevents dev mode to start with a dummy server binary.
fn cleanup_dummy_deps() {
    let Some(target_dir) = find_target_dir() else {
        return;
    };

    let is_windows = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() == "windows";
    let memos_bin = target_dir.join(if is_windows { "memos.exe" } else { "memos" });
    if !memos_bin.exists() {
        return;
    }

    memos_bin
        .metadata()
        .map(|meta| meta.len() == 0 && fs::remove_file(memos_bin).is_ok())
        .ok();
}

// Ask git for the real metadata paths so rebuilds also follow linked worktrees.
fn emit_git_rerun_hints() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap_or_default());
    if manifest_dir.as_os_str().is_empty() {
        return;
    }

    let git_path = |path: &str| -> Option<String> {
        Command::new("git")
            .args(["rev-parse", "--git-path", path])
            .current_dir(&manifest_dir)
            .output()
            .map_or(None, |output| {
                if !output.status.success() {
                    return None;
                }
                let path = String::from_utf8_lossy(&output.stdout).trim().to_owned();
                if path.is_empty() {
                    return None;
                }

                Some(path)
            })
    };

    let Some(head_path) = git_path("HEAD") else {
        return;
    };
    println!("cargo:rerun-if-changed={head_path}");

    if let Some(packed_refs_path) = git_path("packed-refs") {
        println!("cargo:rerun-if-changed={packed_refs_path}");
    }

    Command::new("git")
        .args(["symbolic-ref", "-q", "HEAD"])
        .current_dir(&manifest_dir)
        .output()
        .map(|head_ref_output| {
            if !head_ref_output.status.success() {
                return;
            }

            let head_ref = String::from_utf8_lossy(&head_ref_output.stdout)
                .trim()
                .to_owned();
            if let Some(head_ref_path) = (!head_ref.is_empty())
                .then(|| git_path(&head_ref))
                .flatten()
            {
                println!("cargo:rerun-if-changed={head_ref_path}");
            }
        })
        .ok();
}

fn main() {
    emit_git_rerun_hints();

    env::var("CARGO_MANIFEST_DIR")
        .map(|manifest_dir| {
            if manifest_dir.is_empty() {
                return;
            }
            Command::new("git")
                .args(["rev-parse", "--verify", "HEAD"])
                .current_dir(&manifest_dir)
                .output()
                .map(|output| {
                    let hash = String::from_utf8_lossy(&output.stdout).trim().to_owned();
                    if hash.len() >= 7 {
                        let short_hash = &hash[..7];
                        println!("cargo:rustc-env=GIT_SHORT_HASH={short_hash}");
                        println!("cargo:rustc-env=GIT_HASH={hash}");
                    }
                })
                .ok();
        })
        .ok();

    std::env::var("TARGET")
        .map(|t| println!("cargo:rustc-env=TARGET_TRIPLE={t}"))
        .ok();

    ensure_deps();
    generate_shortcut_artifacts();
    // Runs only on dev and release builds.
    if cfg!(not(feature = "unittest")) {
        cleanup_dummy_deps();
    }
    tauri_build::build()
}
