version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 30
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2

  - package-ecosystem: "cargo"
    directory: "/"
    cooldown:
      default-days: 30
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 30
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: "bun"
    directory: "/"
    cooldown:
      default-days: 30
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: "bun"
    directory: "/build-scripts"
    cooldown:
      default-days: 30
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0

  - package-ecosystem: "bun"
    directory: "/src-ui"
    cooldown:
      default-days: 30
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
