[package]
name = "config"
version = "0.8.0"
authors = ["Lincoln Nogueira"]
edition = "2021"
license = "MIT"
description = "Memospot configuration library"

[dependencies]
figment = { version = "0.10", features = ["env", "yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"

[dev-dependencies]
tempfile = "3.13"
