[package]
name = "config"
version = { workspace = true }
edition = { workspace = true }
publish = false
description = "Memospot configuration library"

[lib]
name = "config"
path = "src/lib.rs"

[dependencies]
figment = { version = "0.10", features = ["env", "yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"

[dev-dependencies]
tempfile = "3.13"
