[package]
name = "dialog"
version = "0.0.1"
authors = ["Lincoln Nogueira"]
edition = "2021"
license = "MIT"
description = "Memospot platform-agnostic dialog utilities"

[dependencies.log]
version = "0.4.21"

[dependencies.native-dialog]
version = "0.7.0"
