[package]
name = "dialog"
version = "0.0.1"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
description = "Memospot platform-agnostic dialog utilities"

[dependencies]
log = "0.4"
native-dialog = "0.7"
