[package]
name = "dialog"
version = "0.0.1"
authors = ["Lincoln Nogueira"]
edition = "2021"
license = "MIT"
description = "Memospot platform-agnostic dialog utilities"

[dependencies]
log = "0.4"
native-dialog = "0.7"
