//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "inbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_ts: i64,
    pub sender_id: i32,
    pub receiver_id: i32,
    pub status: String,
    pub message: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
