//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod activity;
pub mod idp;
pub mod inbox;
pub mod memo;
pub mod memo_organizer;
pub mod memo_relation;
pub mod migration_history;
pub mod resource;
pub mod storage;
pub mod system_setting;
pub mod tag;
pub mod user;
pub mod user_setting;
pub mod webhook;
