//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "memo_relation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub memo_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub related_memo_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
