//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::activity::Entity as Activity;
pub use super::idp::Entity as Idp;
pub use super::inbox::Entity as Inbox;
pub use super::memo::Entity as Memo;
pub use super::memo_organizer::Entity as MemoOrganizer;
pub use super::memo_relation::Entity as MemoRelation;
pub use super::migration_history::Entity as MigrationHistory;
pub use super::resource::Entity as Resource;
pub use super::storage::Entity as Storage;
pub use super::system_setting::Entity as SystemSetting;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
pub use super::user_setting::Entity as UserSetting;
pub use super::webhook::Entity as Webhook;
