//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub creator_id: i32,
    pub created_ts: i64,
    pub updated_ts: i64,
    pub filename: String,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub blob: Option<Vec<u8>>,
    pub external_link: String,
    pub r#type: String,
    pub size: i32,
    pub internal_path: String,
    pub memo_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
