//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_ts: i64,
    pub updated_ts: i64,
    pub row_status: String,
    #[sea_orm(unique)]
    pub username: String,
    pub role: String,
    pub email: String,
    pub nickname: String,
    pub password_hash: String,
    pub avatar_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
