// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Backups = { 
/**
 * Enable backups.
 */
enabled: boolean | null, 
/**
 * Directory where Memospot will store backups.
 */
path: string | null, };
