// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvironmentVariables = { enabled: boolean | null, vars: { [key in string]?: string } | null, };
