// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Migrations = { 
/**
 * Enable database migrations.
 * Can be disabled to use Memospot with an uncertified Memos version.
 */
enabled: boolean | null, };
