#:schema ../gen/schemas/desktop-schema.json
identifier = "external-links"
description = "Allows target _blank links to open in the default browser."
windows = ["*"]
platforms = ["macOS", "windows", "linux"]
permissions = [
    "shell:allow-open",
]

[remote]
urls = [
    "http://localhost:*",
    "http://127.0.0.1:*",
    "tauri://*",
]
