# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "homedir"
version = "0.1.1"
authors = ["eulegang <eulegang@gmail.com>", "Lars Wirzenius", "Lincoln Nogueira"]
edition = "2018"
license = "MIT"
repository = "https://github.com/eulegang/home-dir"
description = "expands home directories in a path"

[dependencies]
home = "0.5.5"
nix = { version = "0.27", features = ["user"] }
thiserror = "1.0"
