[package]
name = "homedir"
version = "0.1.2"
authors = ["eulegang <eulegang@gmail.com>", "Lars Wirzenius", "Lincoln Nogueira"]
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/eulegang/home-dir"
description = "expands home directories in a path"

[dependencies]
home = "0.5"
thiserror = "2.0"

[target.'cfg(not(target_os = "windows"))'.dependencies.nix]
version = "0.29"
features = ["user"]
