[package]
name = "migration"
version = "0.1.2"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies.homedir]
path = "../homedir"
version = "0.1.1"

[dependencies.itertools]
version = "0.12.1"

[dependencies.log]
version = "0.4.21"

[dependencies.sea-orm]
version = "0.12"
default-features = false
features = ["sqlx-sqlite", "runtime-tokio-native-tls"]

[dependencies.sea-orm-migration]
version = "0.12"
default-features = false
# https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime/
features = ["sqlx-sqlite", "runtime-tokio-native-tls"] # runtime-tokio-rustls

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.serde_json]
version = "1.0"
