[package]
name = "migration"
version = "0.1.3"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[target.'cfg(not(local_crates))'.dependencies]
homedir = { path = "../homedir" }

[dependencies]
itertools = "0.13"
log = "0.4"
sea-orm = { version = "1.1.0", default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "1.1.0", default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
