[package]
name = "migration"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
description = "Memospot database migration"

[target.'cfg(not(local_crates))'.dependencies]
homedir = { path = "../homedir" }

[dependencies]
itertools = "0.13"
log = "0.4"
sea-orm = { version = "1.1.0", default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "1.1.0", default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
