name: Audit

on:
  workflow_dispatch:
  schedule: [{ cron: "0 0 * * *" }]
  push:
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.{lock,toml}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: rust audit
        uses: rustsec/audit-check@dd51754d4e59da7395a4cd9b593f0ff2d61a9b95
        with: { token: "${{ secrets.GITHUB_TOKEN }}" }
