name: Back-end Tests

on:
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths:
      - "src-tauri/**/*.rs"
      - "src-tauri/**/Cargo.*"
      - "src-tauri/**/Tauri.toml"
  push:
    branches:
      - main
    paths:
      - "src-tauri/**/*.rs"
      - "src-tauri/**/Cargo.*"
      - "src-tauri/**/Tauri.toml"
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cargo cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.2
        with:
          version: "v0.7.3"

      - name: Run rustfmt
        run: cargo fmt --check
        working-directory: ./src-tauri

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy server binary
        run: |
          mkdir -p ./server-dist
          touch ./server-dist/memos-$(uname -m)-unknown-linux-gnu

      - name: Install Tauri deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libgtk-3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.0-dev \
            patchelf
          sudo apt-get install -y libappindicator3-dev || true

      - name: Install sarif-fmt
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: psastras/sarif-rs
          cache: enable
          tag: "sarif-fmt-v0.4.2"
          platform: unknown-linux-gnu
          extension-matching: disable
          rename-to: sarif-fmt
          chmod: 0755

      - name: Install clippy-sarif
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: psastras/sarif-rs
          cache: enable
          tag: "clippy-sarif-v0.4.2"
          platform: unknown-linux-gnu
          extension-matching: disable
          rename-to: clippy-sarif
          chmod: 0755

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup Cargo cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.2
        with:
          version: "v0.7.3"

      - name: Run clippy
        run: >
          cargo clippy --all-features --all --message-format=json
          | clippy-sarif
          | tee clippy-results.sarif
          | sarif-fmt
        working-directory: ./src-tauri
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: clippy-results.sarif
          wait-for-processing: true
