name: Build (Release)
on:
  push:
    tags-ignore: "v*.*.*-*"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CACHE_KEY: ${{ github.run_id }}-${{ github.run_number }}
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LATEST_MEMOS_VERSION: NOT_SET
  NODE_MODULES: ${{github.workspace}}/node_modules
  RUST_BACKTRACE: short
  RUSTC_WRAPPER: sccache
  RUSTFLAGS: -Copt-level=3 -Cstrip=symbols -Ccodegen-units=1
  SCCACHE_DIR: ${{github.workspace}}/.sccache
  SCCACHE_GHA_ENABLED: false # required to cache everything at once and avoid rate limiting
  APT_DEPS: >-
    build-essential
    curl
    file
    patchelf
    wget
    libayatana-appindicator3-dev
    libgtk-3-dev
    librsvg2-dev
    libssl-dev
    libwebkit2gtk-4.1-dev
    libxdo-dev

jobs:
  publish-release:
    name: Publish
    permissions: { contents: write }
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { runner: macos-13, rust_target: aarch64-apple-darwin }
          - { runner: macos-13, rust_target: x86_64-apple-darwin }
          - { runner: ubuntu-22.04, rust_target: x86_64-unknown-linux-gnu }
          - { runner: windows-2019, rust_target: x86_64-pc-windows-msvc }

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set env vars
      - name: "Set env vars"
        shell: bash
        run: |
          echo CACHE_KEY=$(date +'%Y%m%d') >> $GITHUB_ENV
          latest_memos_version=$(curl -s "https://api.github.com/repos/memospot/memos-builds/releases/latest" | jq -r '.tag_name' || echo "NOT_SET")
          echo "LATEST_MEMOS_VERSION=$latest_memos_version" >> $GITHUB_ENV
      - if: ${{ runner.os == 'Windows' }}
        name: "[Windows] Fix environment variables"
        run: |
          $SCCACHE_DIR = "${{env.SCCACHE_DIR}}".replace("/", "\")
          echo "SCCACHE_DIR=$SCCACHE_DIR" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      # /Set env vars

      - if: ${{ runner.os == 'Linux' }}
        name: "[Linux] Disable initramfs and man-db update"
        continue-on-error: true
        run: |
          sudo mkdir -p /etc/initramfs-tools/
          echo -e 'update_initramfs=no\nbackup_initramfs=no' | sudo tee /etc/initramfs-tools/update-initramfs.conf
          sudo rm -f /var/lib/man-db/auto-update

      - if: ${{ runner.os == 'Linux'  }}
        name: "[Linux] Install platform dependencies"
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad
        with: { packages: "${{env.APT_DEPS}}" }

      - if: ${{ runner.os == 'macOS' }}
        name: "[macOS] Install platform dependencies"
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with: { xcode-version: "latest-stable" }

      - if: ${{ runner.os == 'Linux' }}
        name: "[Linux] Install UPX"
        uses: crazy-max/ghaction-upx@0fc45e912669ba9e8fa2b430e97c8da2a632e29b
        with: { install-only: true }

      - name: Install Just
        uses: taiki-e/install-action@638d0bf357cd5e20410163cdf70545caa82bfa5f
        with: { tool: just@1.36.0 }

      # Rust
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          targets: ${{ runner.os == 'macOS' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          toolchain: stable

      - name: Setup Cargo cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with: { prefix-key: "cargo-${{ matrix.platform.rust_target }}" }
      # /Rust

      # sccache
      - name: Install sccache
        uses: taiki-e/install-action@638d0bf357cd5e20410163cdf70545caa82bfa5f
        with: { tool: sccache@0.8.2 }

      - name: Initialize sccache environment
        shell: bash
        run: sccache --stop-server > /dev/null || true

      - name: Setup sccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ matrix.platform.rust_target }}-${{ env.CACHE_KEY }}
          restore-keys: sccache-${{ matrix.platform.rust_target }}

      - name: Start sccache
        shell: bash
        run: sccache --start-server || (sccache --stop-server && sleep 1 && sccache --start-server)
      # /sccache

      # Bun
      - uses: oven-sh/setup-bun@v2
        with: { bun-version: latest }

      - # node_modules is not cached on Windows as it breaks subsequent runs
        if: ${{ runner.os != 'Windows' }}
        name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: node_modules-${{ runner.os }}
          path: ${{env.NODE_MODULES}}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          key: bundeps-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: bundeps-${{ runner.os }}
          path: ~/.bun

      - name: Install Bun dependencies
        run: just deps-ts
      # /Bun

      - name: Cache Memos builds
        uses: actions/cache@v4
        with:
          key: memosbuilds-cross-${{ env.LATEST_MEMOS_VERSION }}-${{ env.CACHE_KEY }}
          restore-keys: memosbuilds-cross
          enableCrossOsArchive: true
          path: ./server-dist

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@4ec5841d83495da72c665daa556e6f231b89ae06
        continue-on-error: true
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "v__VERSION__"
          releaseBody: |
            > [!TIP]
            > Bundled Memos version: **${{ env.LATEST_MEMOS_VERSION }}**

            See the assets section below to download the app.

            - Windows `exe`: per-user install (recommended).
            - Windows `msi`: per-machine install.
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.platform.rust_target }}
          includeUpdaterJson: true
          updaterJsonPreferNsis: true

      - name: "Cleanup sccache"
        run: "sccache --stop-server"
