name: Build (Release)
on:
  push:
    tags-ignore:
      - "v*.*.*-*"
  workflow_dispatch:
    inputs:
      memos-version:
        description: Memos version to bundle.
        required: false
        type: string
        default: latest

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CACHE_KEY: NOT_SET
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GLIBC_VERSION: NOT_SET
  MEMOS_VERSION: NOT_SET
  RUST_TARGET: NOT_SET
  RUST_BACKTRACE: short
  RUSTFLAGS: -Copt-level=3 -Cstrip=symbols -Ccodegen-units=1

jobs:
  publish-release:
    name: Publish
    permissions: { contents: write }
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { runner: macos-15, rust_target: aarch64-apple-darwin }
          - { runner: macos-15-intel, rust_target: x86_64-apple-darwin }
          - { runner: ubuntu-22.04, rust_target: x86_64-unknown-linux-gnu }
          - { runner: windows-2022, rust_target: x86_64-pc-windows-msvc }
          - { runner: windows-2022, rust_target: aarch64-pc-windows-msvc }

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set env vars"
        shell: bash
        run: |
          echo "RUST_TARGET=${{ matrix.platform.rust_target }}" >> $GITHUB_ENV
          echo "CACHE_KEY=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "GLIBC_VERSION=$(ldd --version | head -n 1 | awk '{print $NF}')" >> $GITHUB_ENV

      - if: ${{ runner.os == 'Linux'  }}
        name: "[Linux] Setup Ubuntu for Tauri builds"
        uses: ./.github/actions/setup-tauri-ubuntu
        with:
          ubuntu-runner: "${{ matrix.platform.runner }}"

      - if: ${{ runner.os == 'macOS' }}
        name: "[macOS] Install platform dependencies"
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: "latest-stable"

      - name: Install Just
        uses: taiki-e/install-action@650c5ca14212efbbf3e580844b04bdccf68dac31
        with:
          tool: just@1.45.0

      #> Rust
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          targets: ${{ matrix.platform.rust_target }}

      - name: Setup Cargo cache
        uses: swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # 2.9.1
        with:
          prefix-key: cargo
          shared-key: ${{ matrix.platform.runner }}-${{ runner.arch }}${{ runner.os == 'Linux' && format('-glibc{0}', env.GLIBC_VERSION) || '' }}
          key: ${{ matrix.platform.rust_target }}-${{ hashFiles('**/Cargo.lock') }}
      #/ Rust

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      #> Memos
      # Allows to bundle a specific Memos version when running the workflow manually.
      - if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.memos-version != ''  }}
        name: Set desired Memos version to ${{ inputs.memos-version }}
        shell: bash
        run: |
          echo "MEMOS_VERSION=${{ inputs.memos-version }}" >> $GITHUB_ENV

      - name: Cache Memos builds
        uses: actions/cache@v5
        with:
          key: memos-${{ matrix.platform.runner }}-${{ matrix.platform.rust_target }}-${{ env.MEMOS_VERSION != 'latest' && env.MEMOS_VERSION || env.CACHE_KEY }}
          restore-keys: memos-${{ matrix.platform.runner }}-${{ matrix.platform.rust_target }}
          path: ./server-dist

      # This is run before building the Tauri app so that the MEMOS_VERSION
      # is set by the downloadMemos script if it was not set via workflow inputs.
      - name: Download Memos
        run: just download-memos
      #/ Memos

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@73fb865345c54760d875b94642314f8c0c894afa
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "v__VERSION__"
          # This will also show on the updater notes.
          releaseBody: |
            Bundled Memos version: **${{ env.MEMOS_VERSION }}**
            Updating from previous versions is transparent.

            [Installation & Safety notes](https://memospot.github.io/guides/installation/)
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.platform.rust_target }}
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          retryAttempts: 2
