name: Build (Test)
on:
  push:
    tags:
      - "v*.*.*-*"
    paths:
      - "**/*.{json,rs,ts}"
      - "**/*.{nsi,nsh,wxs}"
      - "**/build-test.yml"
      - "**/bun.lock"
      - "**/Cargo.{lock,toml}"
      - "**/Tauri.toml"
  workflow_dispatch:
    inputs:
      memos-version:
        description: Memos version to bundle.
        required: false
        type: string
        default: "latest"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CACHE_KEY: NOT_SET
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GLIBC_VERSION: NOT_SET
  MEMOS_VERSION: NOT_SET
  RUST_TARGET: NOT_SET
  RUST_BACKTRACE: short
  RUSTFLAGS: -Copt-level=1 -Cstrip=symbols -Ccodegen-units=16

permissions:
  contents: read

jobs:
  build-test:
    name: Build (Test)
    permissions: { contents: write }
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { runner: macos-15, rust_target: aarch64-apple-darwin }
          - { runner: macos-15-intel, rust_target: x86_64-apple-darwin }
          - { runner: ubuntu-22.04, rust_target: x86_64-unknown-linux-gnu }
          - { runner: windows-2022, rust_target: x86_64-pc-windows-msvc }
          - { runner: windows-2022, rust_target: aarch64-pc-windows-msvc }

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Set env vars"
        shell: bash
        run: |
          echo "RUST_TARGET=${{ matrix.platform.rust_target }}" >> $GITHUB_ENV
          echo "CACHE_KEY=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "GLIBC_VERSION=$(ldd --version | head -n 1 | awk '{print $NF}')" >> $GITHUB_ENV

      #> Platform deps
      - if: ${{ runner.os == 'Linux'  }}
        name: "[Linux] Setup Ubuntu for Tauri builds"
        uses: ./.github/actions/setup-tauri-ubuntu
        with:
          ubuntu-runner: "${{ matrix.platform.runner }}"

      - if: ${{ runner.os == 'macOS' }}
        name: "[macOS] Install platform dependencies"
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90
        with:
          xcode-version: latest-stable
      #/ Platform deps

      - name: Install Just
        uses: taiki-e/install-action@d438492cf8a250514fa2d34b30bc3c0dc37c65ff
        with: { tool: just@1.58.0 }

      #> Rust
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067
        with:
          toolchain: stable
          targets: ${{ matrix.platform.rust_target }}

      - name: Setup Cargo cache
        uses: swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # 2.9.2
        with:
          prefix-key: cargo
          shared-key: ${{ matrix.platform.runner }}-${{ runner.arch }}${{ runner.os == 'Linux' && format('-glibc{0}', env.GLIBC_VERSION) }}
          key: ${{ matrix.platform.rust_target }}-${{ hashFiles('**/Cargo.lock') }}
      #/ Rust

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      #> Memos
      # Allows to bundle a specific Memos version when running the workflow manually.
      - if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.memos-version != ''  }}
        name: Set desired Memos version to ${{ inputs.memos-version }}
        shell: bash
        run: |
          echo "MEMOS_VERSION=${{ inputs.memos-version }}" >> $GITHUB_ENV

      - name: Cache Memos builds
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: memos-${{ matrix.platform.runner }}-${{ matrix.platform.rust_target }}-${{ env.MEMOS_VERSION != 'latest' && env.MEMOS_VERSION || env.CACHE_KEY }}
          restore-keys: memos-${{ matrix.platform.runner }}-${{ matrix.platform.rust_target }}
          path: ./server-dist

      # This is run before building the Tauri app so that the MEMOS_VERSION
      # is set by the download-memos script if it was not set via workflow inputs.
      - name: Download Memos
        run: just download-memos
      #/ Memos

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@1deb371b0cd8bd54025b384f1cd735e725c4060f
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__-pre
          releaseName: "Memospot v__VERSION__-pre"
          releaseBody: |
            Bundled Memos version: **${{ env.MEMOS_VERSION }}**

            [Installation & Safety notes](https://memospot.github.io/guides/installation/)

            > [!WARNING]
            > Things may break.
            >
            > This is an untested pre-release, built with bleeding-edge code.
            > Back up your database before installing this version.

            > [!NOTE]
            > Version identifier is not guaranteed to be unique.
            > Assets may be overwritten by automated builds.

            See the assets section below to download the app.

            **[Commit history](https://github.com/memospot/memospot/commits/${{ github.head_ref || github.ref_name }})**

          releaseDraft: true
          prerelease: true
          args: --verbose --target ${{ matrix.platform.rust_target }}
          uploadUpdaterJson: false

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: memospot-${{ matrix.platform.rust_target }}
          path: |
            ${{ github.workspace }}/target/${{ matrix.platform.rust_target }}/release/bundle/dmg/*.dmg
            ${{ github.workspace }}/target/${{ matrix.platform.rust_target }}/release/bundle/deb/*.deb
            ${{ github.workspace }}/target/${{ matrix.platform.rust_target }}/release/bundle/rpm/*.rpm
            ${{ github.workspace }}/target/${{ matrix.platform.rust_target }}/release/bundle/appimage/*.AppImage
            ${{ github.workspace }}/target/${{ matrix.platform.rust_target }}/release/bundle/msi/*.msi
            ${{ github.workspace }}/target/${{ matrix.platform.rust_target }}/release/bundle/nsis/*.exe
