name: Check (TypeScript)

on:
  merge_group:
  pull_request:
    paths:
      - "**/check-typescript.yml"
      - "**/bun.lock"
      - "**/bunfig.toml"
      - "**/biome.jsonc"
      - "**/*.{ts,svelte}"
  push:
    paths:
      - "**/check-typescript.yml"
      - "**/bun.lock"
      - "**/bunfig.toml"
      - "**/biome.jsonc"
      - "**/*.{ts,svelte}"

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  biome:
    name: TypeScript lint
    continue-on-error: true
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Lint code with Biome
        run: biome ci --css-parse-tailwind-directives=true .

  test:
    name: TypeScript tests
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-slim
          - runner: macos-15
          - runner: windows-2022

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Install dependencies with Bun
        shell: bash
        run: |
          pushd ./build-scripts; bun install; popd
          pushd ./src-ui; bun install; popd

      - name: Run Bun tests
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pushd ./build-scripts; bun test; popd
          pushd ./src-ui; bun test; popd
