name: Deno Tests

on:
  pull_request:
    branches: "*"
    paths:
      - "**/*.{cts,mts,ts,tsx}"
      - "**/deno.{jsonc,lock}"

  push:
    branches: "*"
    paths:
      - "**/*.{cts,mts,ts,tsx}"
      - "**/deno.{jsonc,lock}"

  workflow_dispatch:

env:
  DENO_DIR: ${{github.workspace}}/.deno

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deno-tests:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-22.04
          - runner: macos-11
          - runner: windows-2019

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Install Task
        uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b
        with: { repo: "go-task/task", cache: "enable", tag: "v3.34.1" }

      # Deno
      - name: Install Deno
        uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b
        with: { repo: "denoland/deno", cache: "enable", tag: "v1.39.1" }

      - if: ${{ runner.os != 'Windows' }}
        name: Cache Deno dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          key: denodeps-${{ runner.os }}-${{ hashFiles('**/deno.lock') }}
          restore-keys: denodeps-${{ runner.os }}
          path: |
            ${{env.DENO_DIR}}
            ${{github.workspace}}/node_modules

      - if: ${{ runner.os == 'Windows' }}
        name: Cache Deno dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          key: denodeps-${{ runner.os }}-${{ hashFiles('**/deno.lock') }}
          restore-keys: denodeps-${{ runner.os }}
          path: ${{env.DENO_DIR}}
          # node_modules is not cached on Windows as it breaks subsequent
          # runs, probably because this folder relies on symlinks

      - { name: "Restore Deno dependencies", run: "task ci:deno:cache" }
      # /Deno

      - { name: "Run Deno tests", run: "task ci:deno:tests" }
