name: Deno Tests

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.cts"
      - "**/*.mts"
      - "**/deno.jsonc"
      - "**/deno.lock"

  push:
    branches:
      - "*"
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.cts"
      - "**/*.mts"
      - "**/deno.jsonc"
      - "**/deno.lock"

  workflow_dispatch:

jobs:
  deno-tests:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: "ubuntu-22.04"
          - runner: "macos-11"
          - runner: "windows-2019"

    runs-on: ${{ matrix.platform.runner }}
    steps:
      # Set env vars
      - if: ${{ runner.os == 'Linux' }}
        name: "[Linux] Set env vars"
        run: |
          DENO_DIR="${{github.workspace}}/.deno"
          echo "DENO_DIR=$DENO_DIR" >> $GITHUB_ENV

          DENO_CACHE="$HOME/.cache/deno"
          echo "DENO_CACHE=$DENO_CACHE" >> $GITHUB_ENV

      - if: ${{ runner.os == 'macOS' }}
        name: "[macOS] Set env vars"
        run: |
          DENO_DIR="${{github.workspace}}/.deno"
          echo "DENO_DIR=$DENO_DIR" >> $GITHUB_ENV

          DENO_CACHE="$HOME/Library/Caches/deno"
          echo "DENO_CACHE=$DENO_CACHE" >> $GITHUB_ENV

      - if: ${{ runner.os == 'Windows' }}
        name: "[Windows] Set env vars"
        shell: bash
        run: |
          DENO_DIR="${{github.workspace}}\\.deno"
          echo "DENO_DIR=$DENO_DIR" >> $GITHUB_ENV

          DENO_CACHE="$LOCALAPPDATA\\deno"
          echo "DENO_CACHE=$DENO_CACHE" >> $GITHUB_ENV

          TEMP="$LOCALAPPDATA\\Temp"
          echo "TEMP=$TEMP" >> $GITHUB_ENV
          echo "TMP=$TEMP" >> $GITHUB_ENV
      # /Set env vars

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: go-task/task
          cache: enable
          tag: "v3.33.1"

      - name: Install Deno
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: denoland/deno
          cache: enable
          tag: "v1.39.1"

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          key: denodeps-${{ runner.os }}-${{ hashFiles('**/deno.lock') }}
          restore-keys: denodeps-${{ runner.os }}
          enableCrossOsArchive: false
          path: |
            ${{ env.DENO_CACHE }}
            ${{ env.DENO_DIR }}
            ${{github.workspace}}/node_modules

      - name: Restore Deno dependencies
        run: task ci:deno:cache

      - name: Run Deno tests
        run: task ci:deno:tests
