name: Front-end Tests

on:
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths:
      - "src/**"

  push:
    branches: [main]
    paths:
      - "src/**"

  workflow_dispatch:

jobs:
  eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile
        working-directory: .

      - name: Run eslint check
        run: pnpm lint
        working-directory: .

  # frontend-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v2.2.4
  #       with:
  #         version: 8
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
  #         cache: pnpm
  #         cache-dependency-path: "pnpm-lock.yaml"
  #     - run: pnpm install
  #       working-directory: .
  #     - name: Run frontend build
  #       run: pnpm build
  #       working-directory: .
