name: Lint config files

on:
  pull_request:
    branches: "*"
    paths: "**/*.toml"

  push:
    branches: "*"
    paths: "**/*.toml"

  workflow_dispatch:

env:
  DPRINT_CACHE_DIR: ${{github.workspace}}/.dprint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  taplo:
    name: Lint config files
    runs-on: ubuntu-latest
    steps:
      - name: Set dynamic env vars
        shell: bash
        run: echo DATE_STRING=$(date +'%Y%m%d') >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b
        with: { repo: "go-task/task", cache: "enable", tag: "v3.37.2" }

      - name: Install dprint
        uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b
        with: { repo: "dprint/dprint", cache: "enable", tag: "0.45.0" }

      - name: Install taplo
        run: >
          curl -fsSL https://github.com/tamasfe/taplo/releases/download/0.8.1/taplo-linux-x86_64.gz
          | gzip -d -
          | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Cache dprint plugins
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ${{ env.DPRINT_CACHE_DIR }}
          key: cache-dprint-${{ env.DATE_STRING }}
          enableCrossOsArchive: true
          restore-keys: cache-dprint

      - { name: "Lint config", run: "task ci:lint:config" }
