name: Lint config files

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "**/*.toml"

  push:
    branches:
      - "*"
    paths:
      - "**/*.toml"

  workflow_dispatch:

env:
  DPRINT_CACHE_DIR: ${{github.workspace}}/.dprint

jobs:
  taplo:
    name: Lint config files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: go-task/task
          cache: enable
          tag: "v3.33.1"

      - name: Install dprint
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: dprint/dprint
          cache: enable
          tag: "0.44.0"

      - name: Install Taplo
        run: >
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz
          | gzip -d -
          | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Set date string env var
        shell: bash
        run: |
          echo DATE_STRING=$(date +'%Y%m%d') >> $GITHUB_ENV

      - name: Cache dprint plugins
        uses: actions/cache@v3
        with:
          path: ${{ env.DPRINT_CACHE_DIR }}
          key: cache-dprint-${{ env.DATE_STRING }}
          enableCrossOsArchive: true
          restore-keys: cache-dprint

      - name: lint config
        run: task ci:lint:config
