name: "Publish Release"
on:
  push:
    branches:
      - "release/*.*.*"
    tags:
      - "*.*.*"
  workflow_dispatch:

env:
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          # - platform: 'macos-latest'
          #   args: '--target universal-apple-darwin'
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-latest"
            args: "--target x86_64-unknown-linux-gnu"
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: go-task/task
          cache: enable
          tag: "v3.31.0"

      - name: Setup UPX (Windows and Linux only)
        if: matrix.settings.platform != 'macos-latest'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Cargo cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.2
        with:
          version: "v0.7.3"

      - name: Disable initramfs and man-db update (Ubuntu)
        if: matrix.settings.platform == 'ubuntu-latest'
        run: |
          sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install Ubuntu dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        if: matrix.settings.platform == 'ubuntu-latest'
        continue-on-error: true
        with:
          packages: >-
            build-essential
            curl
            file
            wget
            libgtk-3-dev
            librsvg2-dev
            libssl-dev
            libwebkit2gtk-4.0-dev
            patchelf
            libappindicator3-dev
          version: 1.0

      - name: Install macOS dependencies
        uses: maxim-lobanov/setup-xcode@v1
        if: matrix.settings.platform == 'macos-latest'
        with:
          xcode-version: latest-stable

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Memospot v__VERSION__"
          releaseBody: "See the assets section to download this version and install."
          releaseDraft: true
          prerelease: false
