name: Rust audit

on:
  workflow_dispatch:
  schedule: [{ cron: "0 0 * * *" }]
  push:
    paths:
      - ".github/workflows/rust-audit.yml"
      - "**/Cargo.{lock,toml}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-audit:
    runs-on: ubuntu-latest
    permissions: { issues: write, checks: write }
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Rust audit
        uses: rustsec/audit-check@dd51754d4e59da7395a4cd9b593f0ff2d61a9b95
        with: { token: "${{ secrets.GITHUB_TOKEN }}" }
