name: "Test Build"
on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  DENO_DIR: ${{github.workspace}}/.deno
  NODE_MODULES: ${{github.workspace}}/node_modules
  RUST_BACKTRACE: short
  RUSTC_WRAPPER: sccache
  RUSTFLAGS: -Copt-level=1 -Cstrip=symbols
  SCCACHE_DIR: ${{github.workspace}}/.sccache
  SCCACHE_GHA_ENABLED: false # required to cache everything at once and avoid rate limiting
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

jobs:
  test-tauri-build:
    name: "Test Build"
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: "ubuntu-22.04"
            rust_target: "x86_64-unknown-linux-gnu"
          - runner: "macos-11"
            rust_target: "aarch64-apple-darwin"
          - runner: "macos-11"
            rust_target: "x86_64-apple-darwin"
          - runner: "windows-2019"
            rust_target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set env vars
      - if: ${{ runner.os == 'Windows' }}
        name: "[Windows] Set env vars"
        shell: bash
        run: |
          DENO_DIR="$GITHUB_WORKSPACE\\.deno"
          echo "DENO_DIR=$DENO_DIR" >> $GITHUB_ENV

          NODE_MODULES="$GITHUB_WORKSPACE\\node_modules"
          echo "NODE_MODULES=$NODE_MODULES" >> $GITHUB_ENV

          TEMP="$LOCALAPPDATA\\Temp"
          echo "TEMP=$TEMP" >> $GITHUB_ENV
          echo "TMP=$TEMP" >> $GITHUB_ENV
      # /Set env vars

      - if: ${{ runner.os == 'Linux' }}
        name: "[Linux] Disable initramfs and man-db update"
        continue-on-error: true
        run: |
          if [ -f /etc/initramfs-tools/update-initramfs.conf ]; then
            sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
          else
            sudo mkdir -p /etc/initramfs-tools/
            echo 'update_initramfs=no' | sudo tee -a /etc/initramfs-tools/update-initramfs.conf
          fi
          sudo rm -f /var/lib/man-db/auto-update

      - if: ${{ env.ACT }}
        name: "[ACT] Link apt-get as apt-fast"
        run: |
          sudo cp -l /usr/bin/apt-get /usr/local/sbin/apt-fast
          sudo apt-get update > /dev/null
      - if: ${{ runner.os == 'Linux'  }}
        name: "[Linux] Install platform dependencies"
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: >-
            libappindicator3-dev
            libgtk-3-dev
            librsvg2-dev
            libwebkit2gtk-4.0-dev
            patchelf

      - if: ${{ runner.os == 'macOS' }}
        name: "[macOS] Install platform dependencies"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: go-task/task
          cache: enable
          tag: "v3.33.1"

      - if: ${{ runner.os == 'Linux' }}
        name: "[Linux] Install UPX"
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      # Rust
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.rust_target }}

      - name: Setup Cargo cache
        uses: swatinem/rust-cache@v2
        with:
          prefix-key: cargo-${{ matrix.platform.rust_target }}
      # /Rust

      # sccache
      - name: Install sccache
        uses: taiki-e/install-action@v2
        with:
          tool: sccache@0.7.4

      - name: Initialize sccache environment
        shell: bash
        run: |
          echo DATE_STRING=$(date +'%Y%m%d') >> $GITHUB_ENV
          sccache --stop-server > /dev/null || true

      - name: Setup sccache cache
        uses: actions/cache@v3
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ matrix.platform.rust_target }}-${{ env.DATE_STRING }}
          restore-keys: sccache-${{ matrix.platform.rust_target }}

      - name: Start sccache
        shell: bash
        run: sccache --start-server || (sccache --stop-server && sleep 1 && sccache --start-server)
      # /sccache

      # Deno
      - name: Install Deno
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: denoland/deno
          cache: enable
          tag: "v1.39.1"

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          key: denodeps-${{ runner.os }}-${{ hashFiles('**/deno.lock') }}
          restore-keys: denodeps-${{ runner.os }}
          enableCrossOsArchive: false
          path: |
            ${{env.DENO_DIR}}
            ${{env.NODE_MODULES}}

      - name: Restore Deno dependencies
        run: task ci:deno:cache
      # /Deno

      - name: Cache memos builds
        uses: actions/cache@v3
        with:
          key: memosbuilds-cross-${{ env.DATE_STRING }}
          restore-keys: memosbuilds-cross
          enableCrossOsArchive: true
          path: ./server-dist

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__-pre
          releaseName: "Memospot v__VERSION__-pre"
          releaseBody: |
            See the assets section below to download the app.
          releaseDraft: true
          prerelease: true
          args: --verbose --target ${{ matrix.platform.rust_target }}

      - name: Cleanup sccache
        run: sccache --stop-server
