name: TypeScript lint and test

on:
  pull_request:
    branches: "*"
    paths:
      - ".github/workflows/typescript.yml"
      - "**/*.{ts,tsx}"
      - "**/bun.lockb"
      - "**/package.json"

  push:
    branches: "*"
    paths:
      - ".github/workflows/typescript.yml"
      - "**/*.{ts,tsx}"
      - "**/bun.lockb"
      - "**/package.json"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    name: TypeScript lint
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Biome
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5
        with:
          version: latest

      - name: Lint code with Biome
        run: biome ci . || biome ci .

  test:
    name: TypeScript tests
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-22.04
          - runner: macos-12
          - runner: windows-2019

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      # Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
        with: { bun-version: latest }

      - # node_modules is not cached on Windows as it breaks subsequent runs
        if: ${{ runner.os != 'Windows' }}
        name: Cache node_modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: node_modules-${{ runner.os }}
          path: ${{github.workspace}}/node_modules

      - name: Cache Bun dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          key: bundeps-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: bundeps-${{ runner.os }}
          path: ~/.bun

      - name: Install dependencies with Bun
        shell: bash
        run: bun install --frozen-lockfile || bun install --frozen-lockfile
      # /Bun

      - name: Run Bun tests
        run: bun test || bun test
